services:
  php:
    build: ./php/
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./app:/var/www/html
    ports:
      - '8080:80'
    restart: always
  mysql:
    image: mysql:8.3
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=sevenhalf
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=appuserpwd
    restart: always
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8090:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    restart: always
